[package]
name = "adder"
version = "0.1.0"
authors = ["Kyle Reyes <mr.kylereyes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
