#!/bin/bash

# script runs docker compose for the specified mode.
# script will likely do more startup/teardown functions

MODE=${1:-up} # mode should be either 'up' or 'down'

START_PATH=$(cd .. && pwd)/node_modules/react-scripts/scripts/start.js # Path to start script that `react-scripts start` runs

case $MODE in 
    up)
        # DRUID STACK
        docker-compose up -d # start up druid stack

        # REACT FRONTEND
        npm start & # start up frontend (runs in background)
        # wait for start script to run so we can save the PID
        while ! pgrep -f $START_PATH > /dev/null; do
            sleep 0.1 # delay until next check
        done
        pgrep -f $START_PATH > .pid # start and write pid to a file in the current directory

        ;;
    down)
        # KILL DRUID
        docker-compose down

        # KILL REACT
        kill -15 $(cat .pid)
        rm -f .pid

        ;;
    *)
        echo Mode ${MODE} is not supported
        exit 1
esac
